#define L2MAX 725
#define MAX_THREAD_PER_SM 1536
#define MAX_THREAD_PER_THREAD_BLOCK 1024
#define MARGIN 2
#define MAX_SM 82
#define MAX_AVAILABLE_SM (MAX_SM - MARGIN)
#define THREAD_PER_JOB ((MAX_THREAD_PER_SM * MAX_AVAILABLE_SM) / PART)
#define THREAD_BLOCK_PER_JOB (THREAD_PER_JOB / MAX_THREAD_PER_THREAD_BLOCK)
